apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:2828d69f4037fea891bfccfc7366a6c864b85641a7c18d94535b5272d7903312
  name: dotnet-6.0
  newName: quay.io/rahulbhadouria/mywebapp
