apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:1eba47e0a60e93ee12c0fca4dd5e706fc2a7689a105a4f24031a3e6528e09c0b
  name: dotnet-6.0
  newName: quay.io/rahulbhadouria/mywebapp
