apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:47a746b9ecb97d4e1cd7c9f1a90b5c3df02648bf8b77cbfe2f2ddbb0ccfe50ed
  name: dotnet-6.0
  newName: quay.io/rahulbhadouria/mywebapp
