apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
images:
- digest: sha256:3ac99dce2f6a0a5fd94b39dcd543f2a7cd0875c743b06dc98df9d7e9c5dc0b0a
  name: dotnet-6.0
  newName: quay.io/rahulbhadouria/mywebapp
